spring:
  datasource:
    url: jdbc:h2:mem:product_test_db;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop   # Hibernate tự tạo bảng từ @Entity, không cần schema.sql
    show-sql: true
    properties:
      hibernate:
        format_sql: true
grpc:
  server:
    port: 9000
    enable-reflection: true